mem_region: Fix unused-but-set-variable error
Newer GCC are catching this:

  core/test/../mem_region.c: In function 'start_mem_region_clear_unused':
  core/test/../mem_region.c:1334:18: error: variable 'total' set but not used [-Werror=unused-but-set-variable=]
   1334 |         uint64_t total = 0;

Reviewed-by: Dan Horák <dan@danny.cz>
Signed-off-by: Reza Arbab <arbab@linux.ibm.com>