crypto/mbedtls: Fix unused-but-set-variable error
Newer GCC are catching this:

  libstb/crypto/mbedtls/library/bignum.c: In function 'mpi_mul_hlp':
  libstb/crypto/mbedtls/library/bignum.c:1331:29: error: variable 't' set but not used [-Werror=unused-but-set-variable=]
   1331 |     mbedtls_mpi_uint c = 0, t = 0;

Reviewed-by: Dan Horák <dan@danny.cz>
Signed-off-by: Reza Arbab <arbab@linux.ibm.com>